### ISSUE TITLE
Shotgun menu in 3DE

### ISSUE THREAD

**Issue by andreasmalta1** [splidje/tk-3dequalizer#6]
I'm trying to the integrate between 3DE and SG using the engine provided. When loading 3DE from SG desktop, the shotgun menu is not visible. On the console it is outputting the menu has been created but this is never loaded into 3DE

**Comment by splidje** [comment]
Hello. Which version of 3DE are you using?

**Comment by splidje** [comment]
I've just updated master with changes I hadn't pushed to here yet. Not sure if that'll change anything?

**Comment by andreasmalta1** [comment]
Thanks for the changes but still not working.
I updated to release 7 but I'm having issues with the PyQt imports. Could this be since I'm running Python2.7?

**Comment by andreasmalta1** [comment]
PyQt has been solved from my end but I am still having issues in getting the shotgrid menu visible in 3DE

**Comment by RicardoMusch** [comment]
For me the engine pre_app_init() fails:

`Traceback (most recent call last):
  File "<string>", line 25, in <module>
  File "C:\Users\ricardom\AppData\Roaming\Shotgun\acme\p485c1717.basic.desktop\cfg\install\core\python\tank\platform\engine.py", line 3013, in start_engine
    return _start_engine(engine_name, tk, None, context)
  File "C:\Users\ricardom\AppData\Roaming\Shotgun\acme\p485c1717.basic.desktop\cfg\install\core\python\tank\platform\engine.py", line 3173, in _start_engine
    engine = class_obj(tk, new_context, engine_name, env)
  File "S:\_cache\shotgrid\bundle_cache\git\tk-3dequalizer.git\v0.1.0\engine.py", line 24, in __init__
    Engine.__init__(self, *args, **kwargs)
  File "C:\Users\ricardom\AppData\Roaming\Shotgun\acme\p485c1717.basic.desktop\cfg\install\core\python\tank\platform\engine.py", line 198, in __init__
    self.pre_app_init()
  File "S:\_cache\shotgrid\bundle_cache\git\tk-3dequalizer.git\v0.1.0\engine.py", line 43, in pre_app_init
    if not QtCore.QCoreApplication.instance():
AttributeError: 'NoneType' object has no attribute 'QCoreApplication'`

**Comment by RicardoMusch** [comment]
Right, installed PySide2 inside 3de so that works now but indeed still no menu showing up in 3de 7

**Comment by skeleturtle** [comment]
I can't seem to get any Qt modules to import. What did ya'll do?

**Comment by ValeriyVG** [comment]
If someone still needs it. I found some issues and I could share. It works for me after I fixed them.

**Comment by slegrandNut** [comment]
> If someone still needs it. I found some issues and I could share. It works for me after I fixed them.

Hello Valeriy, I'm interested if you have some input :-) thanks in advance

**Comment by claxtt1123** [comment]
Was this ever resolved? @ValeriyVG.  I am trying to implement this and its not showing up the menu on the main window.

**Comment by slegrandNut** [comment]
I found a solution on this other repo: https://github.com/wwfxuk/tk-3de4/blob/master/startup/startup.py

When i contacted original 3de developper he explained to me the same trick, as there is no loop to update Qt interfaces you have to set one, by settings it in the shotgrid engine launch it allow Qt interfaces to work for all Ui inside 3DE

This repo has also the advantage of proposing quite some hooks for legacy sgtk apps

**Comment by ValeriyVG** [comment]
Hi @claxtt1123 , @slegrandNut
Somehow I missed your messages, sorry guys. I have not visited this page for years, accidentally jumped here, saw your requests and decided to write the reply as  I guess better late than never...
As I  see some updates have been released here , so I hope you finally integrated 3de in your pipelines.
regards.
